### ISSUE TITLE
Cannot find CUDA_HOME in second pip install

### ISSUE THREAD

**Issue by kajodataservices** [Snowflake-Labs/llm-bootcamp-build-2023#40]
I can't get past the second pip install.

Kernal: llm-bootcamp (Python 3.9.18)

%pip install peft transformers==4.34.0 tokenizers vllm==0.2.1.post1 bitsandbytes datasets absl-py==1.3.0

Collecting peft
  Using cached peft-0.7.0-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: transformers==4.34.0 in [c:\users\onlin\anaconda3\envs\llm-bootcamp\lib\site-packages](file:///C:/users/onlin/anaconda3/envs/llm-bootcamp/lib/site-packages) (4.34.0)
Requirement already satisfied: tokenizers in [c:\users\onlin\anaconda3\envs\llm-bootcamp\lib\site-packages](file:///C:/users/onlin/anaconda3/envs/llm-bootcamp/lib/site-packages) (0.14.1)
Collecting vllm==0.2.1.post1
  Using cached vllm-0.2.1.post1.tar.gz (132 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "c:\Users\onlin\anaconda3\envs\llm-bootcamp\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\Users\onlin\anaconda3\envs\llm-bootcamp\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\Users\onlin\anaconda3\envs\llm-bootcamp\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\onlin\AppData\Local\Temp\pip-build-env-mz5okz2y\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\onlin\AppData\Local\Temp\pip-build-env-mz5okz2y\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\onlin\AppData\Local\Temp\pip-build-env-mz5okz2y\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 28, in <module>
      RuntimeError: Cannot find CUDA_HOME. CUDA must be available to build the package.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by BPMData** [comment]
I tried for hours and never got the notebooks to run locally. You need to use the notebook in the Jupyter-Lab environment you get from running:

create service FINETUNE_LLM_SERVICE
  MIN_INSTANCES = 1
  MAX_INSTANCES = 1
  COMPUTE_POOL = COMPUTE_POOL_USER####
  SPEC = '@yaml_stage/llm-bootcamp.yaml';

select 
  v.value:containerName::varchar container_name
  ,v.value:status::varchar status  
  ,v.value:message::varchar message
from (select parse_json(system$get_service_status('FINETUNE_LLM_SERVICE'))) t, 
lateral flatten(input => t.$1) v;

show endpoints in service FINETUNE_LLM_SERVICE;

**Comment by kajodataservices** [comment]
I got those commands to work in a Snowflake worksheet.
I have tried to run the Jupyter notebook commands in both Visual Studio Code (Jupyter extension) and Jupyter Notebook but I get the error above.
I noticed someone else posted the same error during the session but I can't find the resolution.

**Comment by kajodataservices** [comment]
I actually narrowed it down to the vllm==0.2.1.post1 package.  I tried installing without the version and it still erred with the same error.
